"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Data(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POLLUTION_DATA_FIELD_NUMBER: builtins.int
    METEO_DATA_FIELD_NUMBER: builtins.int
    pollution_data: builtins.str
    meteo_data: builtins.str
    def __init__(
        self,
        *,
        pollution_data: builtins.str = ...,
        meteo_data: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["meteo_data", b"meteo_data", "pollution_data", b"pollution_data"]) -> None: ...

global___Data = Data
