# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x04\x64\x61ta\x1a\x1bgoogle/protobuf/empty.proto\"E\n\x04\x44\x61ta\x12\x16\n\x0epollution_data\x18\x01 \x01(\t\x12\x12\n\nmeteo_data\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x05\x32:\n\x07\x44\x61taRPC\x12/\n\x07GetData\x12\n.data.Data\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_DATA = DESCRIPTOR.message_types_by_name['Data']
Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:data.Data)
  })
_sym_db.RegisterMessage(Data)

_DATARPC = DESCRIPTOR.services_by_name['DataRPC']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATA._serialized_start=49
  _DATA._serialized_end=118
  _DATARPC._serialized_start=120
  _DATARPC._serialized_end=178
# @@protoc_insertion_point(module_scope)
