# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x1a\x1bgoogle/protobuf/empty.proto\"L\n\x12ProcessedMeteoData\x12\r\n\x05lb_id\x18\x01 \x01(\x05\x12\x14\n\x0c\x61ir_wellness\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\x05\"Y\n\x16ProcessedPollutionData\x12\x1d\n\x15pollution_coefficient\x18\x01 \x01(\x02\x12\r\n\x05lb_id\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x05\x32\x98\x01\n\x06Server\x12\x42\n\x11ReceivedMeteoData\x12\x13.ProcessedMeteoData\x1a\x16.google.protobuf.Empty\"\x00\x12J\n\x15ReceivedPollutionData\x12\x17.ProcessedPollutionData\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_PROCESSEDMETEODATA = DESCRIPTOR.message_types_by_name['ProcessedMeteoData']
_PROCESSEDPOLLUTIONDATA = DESCRIPTOR.message_types_by_name['ProcessedPollutionData']
ProcessedMeteoData = _reflection.GeneratedProtocolMessageType('ProcessedMeteoData', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSEDMETEODATA,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:ProcessedMeteoData)
  })
_sym_db.RegisterMessage(ProcessedMeteoData)

ProcessedPollutionData = _reflection.GeneratedProtocolMessageType('ProcessedPollutionData', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSEDPOLLUTIONDATA,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:ProcessedPollutionData)
  })
_sym_db.RegisterMessage(ProcessedPollutionData)

_SERVER = DESCRIPTOR.services_by_name['Server']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROCESSEDMETEODATA._serialized_start=45
  _PROCESSEDMETEODATA._serialized_end=121
  _PROCESSEDPOLLUTIONDATA._serialized_start=123
  _PROCESSEDPOLLUTIONDATA._serialized_end=212
  _SERVER._serialized_start=215
  _SERVER._serialized_end=367
# @@protoc_insertion_point(module_scope)
