# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n\x0cTempHumidity\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08humidity\x18\x02 \x01(\x02\"T\n\tMeteoData\x12\x11\n\tsensor_id\x18\x01 \x01(\x05\x12!\n\nmeteo_data\x18\x02 \x01(\x0b\x32\r.TempHumidity\x12\x11\n\ttimestamp\x18\x04 \x01(\x05\"B\n\rPollutionData\x12\x0b\n\x03\x63o2\x18\x01 \x01(\x02\x12\x11\n\tsensor_id\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x05\x32\x8a\x01\n\x0cLoadBalancer\x12\x38\n\x10ProcessMeteoData\x12\n.MeteoData\x1a\x16.google.protobuf.Empty\"\x00\x12@\n\x14ProcessPollutionData\x12\x0e.PollutionData\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_TEMPHUMIDITY = DESCRIPTOR.message_types_by_name['TempHumidity']
_METEODATA = DESCRIPTOR.message_types_by_name['MeteoData']
_POLLUTIONDATA = DESCRIPTOR.message_types_by_name['PollutionData']
TempHumidity = _reflection.GeneratedProtocolMessageType('TempHumidity', (_message.Message,), {
  'DESCRIPTOR' : _TEMPHUMIDITY,
  '__module__' : 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:TempHumidity)
  })
_sym_db.RegisterMessage(TempHumidity)

MeteoData = _reflection.GeneratedProtocolMessageType('MeteoData', (_message.Message,), {
  'DESCRIPTOR' : _METEODATA,
  '__module__' : 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:MeteoData)
  })
_sym_db.RegisterMessage(MeteoData)

PollutionData = _reflection.GeneratedProtocolMessageType('PollutionData', (_message.Message,), {
  'DESCRIPTOR' : _POLLUTIONDATA,
  '__module__' : 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:PollutionData)
  })
_sym_db.RegisterMessage(PollutionData)

_LOADBALANCER = DESCRIPTOR.services_by_name['LoadBalancer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEMPHUMIDITY._serialized_start=78
  _TEMPHUMIDITY._serialized_end=131
  _METEODATA._serialized_start=133
  _METEODATA._serialized_end=217
  _POLLUTIONDATA._serialized_start=219
  _POLLUTIONDATA._serialized_end=285
  _LOADBALANCER._serialized_start=288
  _LOADBALANCER._serialized_end=426
# @@protoc_insertion_point(module_scope)
